### ISSUE TITLE
Planeswalker starting loyalty isn't saved anywhere

### ISSUE THREAD

**Issue by dcollinsn** [pbaranay/django-magic-cards#19]
Per `models.py`, I don't see anywhere that a Planeswalker card's starting loyalty is saved.

Similarly, color indicators are probably missing. Anything else you can think of?

**Comment by pbaranay** [comment]
> Similarly, color indicators are probably missing.

MTGJSON does not reveal the color indicator specifically, but its `colors` attribute has the necessary information. I would also add `color_identity`.
